### ISSUE TITLE
Build Windows wheels on appveyor

### ISSUE THREAD

**Issue by rfvermut** [scoder/lupa#103]
I see some work was done in #89, #67 and related towards Windows binaries but no visible outcome. I had to set up my local appveyor repo to get some predictability: https://github.com/MysteriaLV/lupa

But I would like to contribute to help and fix this issue for everyone. You mentioned you don't want to tie lupa to one specific lua version. Can we build both flavors? 

Having at least *some* permutation is better than nothing, right?

**Comment by scoder** [comment]
I added LuaJIT as a submodule, next to Lua 5.3 under `third-party/`, so that both can be used in binary builds.

**Comment by rfvermut** [comment]
README.rst tests are failing for some strange reason: https://ci.appveyor.com/project/rfvermut/lupa-pta21/build/job/7lewwn87x2r59cc7

**Comment by scoder** [comment]
Looks like I got it working myself: https://github.com/scoder/lupa/blob/master/appveyor.yml

The next release should have Windows wheels.

**Comment by rfvermut** [comment]
Can I see the logs? What about luajit?

**Comment by scoder** [comment]
I didn't include luajit. Logs are here:
https://ci.appveyor.com/project/St/lupa/build/1.0.11

**Comment by rfvermut** [comment]
great. lua/luajit are intechangable?

**Comment by scoder** [comment]
> lua/luajit are interchangeable?

Not from a static build perspective. Building luajit is not currently supported as part of the build. Don't know how difficult it would be to add support. Different ticket, I guess. :)

**Comment by scoder** [comment]
Lupa 1.7 released, including Windows wheels.
