### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SoulSen** [scoder/lupa#105]
Can Lupa take in multiple functions? If so how would I distinguish them?

**Comment by scoder** [comment]
Don't know what you mean. Could you give an example? (The answer is probably "Yes, by name", but it's difficult to say without understanding the question.)

**Comment by SoulSen** [comment]
So, `function(num, py_func) 
  return py_func(num) 
end

function(py_func, num) 
  return py_func(num) 
end`. How would I get one function? Cause it errors whenever I try `import lupa
from lupa import LuaRuntime
lua = LuaRuntime(unpack_returned_tuples=True)

def add_one(num):
  return num + 1

with open('main.lua') as c:
  info = c.read()

lua_func = lua.eval(info)

print(lua_func(48, add_one))`
