### ISSUE TITLE
Import deprecation warning from Python 3.7

### ISSUE THREAD

**Issue by dcecile** [scoder/lupa#107]
Running Lupa in Python 3.7, I noticed this deprecation warning:

`.../lib/python3.7/site-packages/lupa/__init__.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

I think it's this import from [lupa/_lupa.pyx](https://github.com/scoder/lupa/blob/master/lupa/_lupa.pyx#L46):

```python
from collections import Mapping
```

Switching the import to `collections.abc` won't work for Python 2, so an extra check would be needed... ([Six](https://github.com/benjaminp/six/issues/155) has an open issue)

**Comment by scoder** [comment]
Thanks, fixed in lupa 1.8.
