### ISSUE TITLE
Unexpected UnicodeDecodeError

### ISSUE THREAD

**Issue by Le0Developer** [scoder/lupa#112]
An unexpected UnicodeDecodeError will occur if you access charpatter in the utf8 table.

```python
>>> import lupa
>>> lua = lupa.LuaRuntime()
>>> lua.globals()[ 'utf8' ][ 'charpattern' ]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lupa/_lupa.pyx", line 643, in lupa._lupa._LuaObject.__getitem__
  File "lupa/_lupa.pyx", line 660, in lupa._lupa._LuaObject._getitem
  File "lupa/_lupa.pyx", line 1117, in lupa._lupa.py_from_lua
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 4: invalid continuation byte
```

**Comment by scoder** [comment]
Hmm, yes, [charpattern](https://q-syshelp.qsc.com/Content/Control_Scripting/Lua_5.3_Reference_Manual/Standard_Libraries/4_-_Basic_UTF-8_Support.htm) is not a valid UTF-8 string, but your `LuaRuntime` is configured to decode Lua strings from UTF-8.

You could disable the automatic decoding of your runtime (or create a new runtime without decoding just to get at the value), but I wonder what you would do with it then. Is there an actual use case for accessing this value from Python?

**Comment by scoder** [comment]
Closing as incomplete, lacking a use case.
