### ISSUE TITLE
What does encoding=None do with unicode strings ?

### ISSUE THREAD

**Issue by tzickel** [scoder/lupa#113]
Why does this return False (at least on python 2)?:
```python
lupa.LuaRuntime(encoding=None).eval('function(a,b) return a==b; end')(u'a',u'a')
```

**Comment by scoder** [comment]
If encoding is disabled, unicode/text strings are wrapped as arbitrary Python objects. That means that there isn't all that much you can do with them inside of Lua, besides passing them through to other Python code.

**Comment by tzickel** [comment]
This is kinda of surprising and unexpected, maybe documentation should be added ?

נשלח מה-iPhone שלי

‫ב-24 ביוני 2019, בשעה 20:26, ‏‏Stefan Behnel ‏<notifications@github.com> כתב/ה:‬

**Comment by scoder** [comment]
What behaviour would you have expected?
