### ISSUE TITLE
Problems running Mandelbrot demo

### ISSUE THREAD

**Issue by zondo** [scoder/lupa#114]
I tried the Mandelbrot demo in the main text, and got a couple of errors (Windows 10, Python 3, lupa 1.8).  I fixed them as follows:

- line 3: change to 'local char, unpack = string.char, table.unpack'
- line 51: change to 'from PIL import Image'

First looks like a typo ('unpack' should be 'table.unpack'), second is due to using Pillow instead of PIL.

After the fixes... OMG that is quite fast! :-)

**Comment by scoder** [comment]
Care to send a PR?

**Comment by scoder** [comment]
Fixed in Lupa 1.9.
f81ea98bd43f0157e62ba78e92e7f04a12b77974
