### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by JakobDev** [scoder/lupa#115]
I have 2 Questions:

1. Can I use Lua 5.1 instead of 5.3?

2. Is it possible to run lua code in a custom environment where it has no access to normal python functions?

**Comment by scoder** [comment]
> 1. Can I use Lua 5.1 instead of 5.3?

Probably. Haven't tried it in a while, though.

> 2. Is it possible to run lua code in a custom environment where it has
> no access to normal python functions?

Yes, you can implement your own access control for Python objects.

**Comment by JakobDev** [comment]
@scoder Have you examples? I haven't found anything in the Readme.

**Comment by scoder** [comment]
https://github.com/scoder/lupa#restricting-lua-access-to-python-objects
