### ISSUE TITLE
undefined symbol: luaopen_lupa - Centos 7

### ISSUE THREAD

**Issue by Liametc** [scoder/lupa#116]
Hi there, 
Trying to build and run Lupa. Got it to build fine, but then can't import it in lua. It errors with 

> LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
> JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> \> require("lupa")
> error loading module 'lupa' from file '/tmp/lupa_install/lib64/python2.7/site-packages/lupa-1.8-py2.7-linux-x86_64.egg/lupa/_lupa.so':
>         /tmp/lupa_install/lib64/python2.7/site-packages/lupa-1.8-py2.7-linux-x86_64.egg/lupa/_lupa.so: undefined symbol: luaopen_lupa
> stack traceback:
>         [C]: at 0x0044cf70
>         [C]: in function 'require'
>         stdin:1: in main chunk
>         [C]: at 0x004050b0

I've attached my dockerfile so you can see if I've gone wrong anywhere. I've tried to follow the installation instructions as closely as possible. This is on a centos 7 system and will be running luaJIT-2.1.0 due to that version being used in another piece of software using it. (Katana if you must know). I have also had this issue with lua-5.1, and luaJIT-2.0.4, whether I build them or install them with `yum`.
[Dockerfile.txt](https://github.com/scoder/lupa/files/3496690/Dockerfile.txt) (sorry it's a txt file, only way to get it to upload. Remove the extension)

Also here is the output of `nm` on the _lupa.so file 
[nm_output.txt](https://github.com/scoder/lupa/files/3496677/nm_output.txt)
`luaopen_lupa` does not appear listed at all

Any help will be appreciated

Thank you

**Comment by Liametc** [comment]
I tried the python bindings and it appears to be working fine, so just concerned with the lua bindings on this one

**Comment by scoder** [comment]
That's not how this works. `lupa` is a module that you import from Python, not from Lua.
