### ISSUE TITLE
Turn LUA table into Dict?

### ISSUE THREAD

**Issue by Kocrachon** [scoder/lupa#118]
Not sure if I see this function, but the ability to get back LUA tables and have it turned into a proper dictionary would be nice for when moving data around and final ouputs.

**Comment by scoder** [comment]
The "obvious" approach works for me:
```python
>>> from lupa import LuaRuntime as Lua
>>> l = Lua()
>>> l.table_from({1:2, 3:4})
<Lua table at 0x4182adf8>
>>> dict(l.table_from({1:2, 3:4}))
{1: 2, 3: 4}
```

**Comment by kebab-mai-haddi** [comment]
Does this work for circular references? Would it completely unpack all the key values?
