### ISSUE TITLE
Keep table order when eval()

### ISSUE THREAD

**Issue by Dimbreath** [scoder/lupa#131]
```
>>> import lupa
>>> lua = lupa.LuaRuntime(unpack_returned_tuples=True)
>>> table = lua.eval('{[20] = -20,[3] = -3,[1] = 0}')
>>> list(table.keys())
[20, 1, 3]
```

Is it possible to keep the order of the table when running eval()? Instead of it being [20, 1, 3] it would be [20, 3, 1]?
The reason for this is that I want to specifically avoid sorting in Python, while it's not an issue with tables that have only integers, it's not really feasible to sort if it's mixed types:

```
>>> table = lua.eval('{[20] = -20,[3] = -3, hello = 0}')
>>> list(table.keys())
[20, 'hello', 3]
```

**Comment by scoder** [comment]
The mapping part of tables in Lua is not ordered. Only the positional items in a Lua table are ordered.
The mapping order returned by `.keys()` in Lupa (and other forms of iteration) is the order provided by Lua, which is arbitrary.
