### ISSUE TITLE
Segfault when using None as dict key in table_from()

### ISSUE THREAD

**Issue by kirillyar** [scoder/lupa#137]
Python 3.7.2

```
from lupa import LuaRuntime

lua_runtime = LuaRuntime()
lua_runtime.table_from({None: {}})
```

**Output**
python[27326]: segfault at 1 ip 0000000000000001 sp 00007ffe1475e9f8 error 14 in python[400000+290000]

**Comment by scoder** [comment]
Confirmed. I guess `None` / `null` dict/table keys are not a good idea. PR welcome that prevents this case by checking for `None` explicitly while copying the items.
