### ISSUE TITLE
Question: Why does Lupa not compile valid Lua?

### ISSUE THREAD

**Issue by DenLilleMand** [scoder/lupa#139]
Hi

I have a ton of Lua snippets in a database, which is rather impractical to modify programmatically. A lot of them have a form like:
```
--define variables
harmonics = 'harmonics'
c_p = 'L2'
--choose the harmonics
if c_p == 'L2' then;
    value = harmonics 
else;
    value = 0.0
end
print(value)
```

I am trying to compile it with Lupa using this code:
```
    lua = lupa.LuaRuntime()
    try:
        lua.compile(value)
    except lupa.LuaSyntaxError as err:
        raise ValidationError(f"Invalid Lua syntax: {err}")
```
And it seems like Lupa does not like the semi-colons after `then` and `else`, i understand that putting those semi-colons is slightly retarded, and i will consider just programmatically removing them before checking with Lupa. But When i run that very same code with Lua 5.2 it works just fine. So Lupa only supports some non-retarded subset or am i missing something?

**Comment by scoder** [comment]
Seems worth checking which Lua version it's using. Probably not 5.2.

**Comment by DenLilleMand** [comment]
> Seems worth checking which Lua version it's using. Probably not 5.2.

Arg, you're right, upgrading Lupa to use 1.9 actually made this work, i guess 1.9 started using 5.2?
