### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by whitewindoff897** [scoder/lupa#140]
![photo_2020-05-19_13-43-44](https://user-images.githubusercontent.com/65601066/82320361-caf28380-99db-11ea-8aa7-c6e11eecd1b9.jpg)

HELP. I install module for pip install, is dont help

**Comment by scoder** [comment]
Did you try `python -m pip install lupa` ? (With whatever `python` or `python3` you are using to run the above program.)

BTW, it's not a good idea to install and run arbitrary packages as `root` user.

**Comment by whitewindoff897** [comment]
> Ты пробовал `python -m pip install lupa`? (С чем угодно, `python`или `python3`вы используете для запуска вышеуказанной программы.)
> 
> Кстати, не очень хорошая идея устанавливать и запускать произвольные пакеты от имени `root`пользователя.

python 3, Yes, the lupa module is installed.

**Comment by scoder** [comment]
Hmm, according to the error message, it's not.
Can you execute `from lupa import LuaRuntime` in the exact same Python interpreter? (You might want to double check that it's really the one that you use for running the program. *And* that you installed `lupa` into that one.)

**Comment by whitewindoff897** [comment]
Sorry for the trouble, the module was installed incorrectly, reinstallation helped. Thanks for the help =)
