### ISSUE TITLE
Windows wheels for Python 3.9

### ISSUE THREAD

**Issue by AcidWeb** [scoder/lupa#150]
AppVeyor added suport for 3.9 some time ago. I would appreciate if 3.9 wheels would be made.

**Comment by NoutieH** [comment]
+1, I would like that as well.

**Comment by scoder** [comment]
I just released Lupa 1.10 with wheels for Py3.9.

**Comment by AcidWeb** [comment]
Only Linux ones. Windows end on 3.8.

**Comment by scoder** [comment]
Right. Looks like Appveyor doesn't have support for Py3.9. That means we'll need a more extensive setup. Help is welcome.

**Comment by AcidWeb** [comment]
Your AppVeyor configuration use `Visual Studio 2015` image. 3.9 is included in `Visual Studio 2019` one.

https://www.appveyor.com/docs/windows-images-software/#python

**Comment by scoder** [comment]
Wheels are now available for Lupa 1.11.
