### ISSUE TITLE
Incorrect conversion

### ISSUE THREAD

**Issue by SamblySok0** [scoder/lupa#161]
Incorrect integer conversion, something like,

```python
import lupa

L = lupa.LuaRuntime()

print(L.eval('822988400906862643'))
```

Output: `822988400906862592`

**Comment by SamblySok0** [comment]
System: Debian/Buster 4.19.0-16-amd64
Python: Python 3.8.7 [GCC 8.3.0]

**Comment by scoder** [comment]
This is due to the usage of double precision floating point numbers internally.

**Comment by SamblySok0** [comment]
> This is due to the usage of double precision floating point numbers internally.

and how i can fix that?
