### ISSUE TITLE
Alternative way to pass keyword arguments to Python functions in Lua

### ISSUE THREAD

**Issue by guidanoli** [scoder/lupa#176]
**Issue:**
There is no clean way to call an arbitrary Python method/function with keyword arguments in Lua.

**Current situation:**
Currently the only way to do so would be by evaluating a Python lambda function in Lua which would somehow convert some positional arguments into keyword arguments, but that's not only ugly but inefficient.

**Suggestion:**
If we want to call a function with keyword arguments, there should be no need to wrap the function in some type of decorator (like is done currently with `unpacks_lua_table` and `unpacks_lua_table_method`). This should be done in the function call, for example, with a table constructor with a unique metatable which identifies a table as a set of keyword arguments:

```lua
python.builtins.print(1, 2, 3, python.kwargs{sep=', '}) -- Prints "1, 2, 3"
python.builtins.dict(python.kwargs{a=1, b=2})           -- {"a": 1, "b": 2}
```

**Comment by scoder** [comment]
Right. Lupa cannot distinguish between a Lua table being passed as table and the intention of passing keyword arguments into a function.  Both are legitimate use cases.

**Comment by scoder** [comment]
Although, maybe we should just wrap all Python builtins automatically with `unpacks_lua_table()`? They certainly wouldn't understand Lua tables otherwise. Although there is also a bit of a use case for `print(some_lua_table)`, for debugging, but given that it doesn't really print anything greatly helpful, we might as well go for the more likely use case.

**Comment by guidanoli** [comment]
> Although, maybe we should just wrap all Python builtins automatically with `unpacks_lua_table()`? They certainly wouldn't understand Lua tables otherwise. Although there is also a bit of a use case for `print(some_lua_table)`, for debugging, but given that it doesn't really print anything greatly helpful, we might as well go for the more likely use case.

Wrapping the built-in functions with `unpacks_lua_table` doesn't solve the problem, because the user might want to call his functions with keyword arguments and wrapping all these with this decorator is just a bad smell. Also, wrapping Python methods in Lua is weird, because the wrapped function is not bound to the instance anymore. E.g.

```python
# In Python
class MyClass:
  def mymethod(self, *args, **kwargs):
    return args, kwargs
```

```lua
-- In Lua
my_class = python.eval('MyClass')
my_instance = my_class()

-- Option A
my_instance.mymethod(1, 2, 3, python.kwargs{a=1, b=2, c=3})

-- Option B
local lupa = python.builtins.__import__('lupa')
local mywrappedfunc = lupa.unpacks_lua_table(my_instance.mymethod)
mywrappedfunc{my_instance, 1, 2, 3, a=1, b=2, c=3}
```

So instead of wrapping the built-in functions (which might be unintuitive that they unpack Lua tables 'out-of-the-box'), passing python.kwargs{...} at the end just seems like a better option.
