### ISSUE TITLE
Provide all of Lua 5.3/5.4 and LuaJIT in a single package

### ISSUE THREAD

**Issue by romanalexander** [scoder/lupa#196]
The distributions from pip use the bundled Lua 5.3 implementation, not LuaJIT2.0.5 as the readme suggests

**Comment by scoder** [comment]
Hmm. Given how small the Lua implementations are, I think it would be cool if the Lupa wheels shipped just all available options, say, Lua 5.3/4 and LuaJIT, as a Package. Then importing "lupa" would just give you the latest Lua 5.x, as it's the case now, and importing "lupa.luajit2" would give you the same API but built with LuaJIT 2.x. This could all come from the current module implementation with a more elaborate build setup.

PR very welcome.

**Comment by scoder** [comment]
Module names to provide:
- `lupa` - `from .lua54 import *` (i.e. delegating to latest Lua module)
- `lupa.lua53` - Lua 5.3.x
- `lupa.lua54` - Lua 5.4.x
- `lupa.luajit20` - LuaJIT 2.0.x
- `lupa.luajit21` - LuaJIT 2.1.x

**Comment by tatuylonen** [comment]
I strongly support making lupa available with different Lua versions!  I'm using lupa extensively for Wiktionary extraction (https://github.com/tatuylonen/wiktextract, or actually its subpackage https://github.com/tatuylonen/wikitextprocessor).  Wiktionary uses Lua 5.2, and I have no way of upgrading the Wiktionary modules to Lua 5.3 or 5.4.  I've coped with Lua 5.3 by patching the Lua source code using essentially a few dozen regexp-replaces, but it is a horrible kludge.  Now with Lua 5.4, it has again changed in several incompatible ways, including changes in supported format strings and apparently the operation of metatables has also changed in subtle ways.  It's coming to a point where I'll have to start building and releasing my own version of lupa compiled for an older version unless there is support for either selecting the version to use when creating a Lua context or installing a separate package.  The proposed way of, e.g., lupa.lua53 works, but I would very much prefer using Lua 5.2.  The English Wiktionary alone contains 322,000 lines of Lua 5.2 code, and when counting the other language editions and Wikipedia, it is probably millions of lines of Lua 5.2 code in Mediawiki projects alone.  It is not going to get upgraded from Lua 5.2 any time soon, I think.

I came to this repository with the intention of submitting an issue to request this feature.

**Comment by scoder** [comment]
See #207

**Comment by scoder** [comment]
There is currently no build procedure for LuaJIT (although the sources are bundled) and building Lua 5.2.3 also fails.
Help with that is welcome, otherwise I'd just keep it as it is for now.

**Comment by scoder** [comment]
I got LuaJIT to build at least on Linux. That way, it can be used with a conditional import and a fallback to normal Lua.

**Comment by scoder** [comment]
The PR is mostly working now. I'm not sure about the interface, though. It seems clumsy to write
```python
import lupa.lupa_lua54 as lupa
```
Also, `import lupa` currently imports the Lua 5.4 version, so `import lupa.lupa_lua53` loads both Lua 5.3 and Lua 5.4.

Rather, it would be nice to say
```python
import lupa.lua53 as lupa
```
and have `import lupa` basically do nothing. But that's backwards incompatible (which would be acceptable for the intended Lupa 2.0 but not great) and also seems a bit less clear – `from lupa import lua53` returns the same kind of module as `from lupa import lua54`, just with a different Lua version.

Comments welcome.

**Comment by scoder** [comment]
The incompatibility can be resolved with PEP 562 (module level `__getattr__`), that's done.

That makes `from lupa import lua53` more appealing now. I changed the module names as well.
