### ISSUE TITLE
Missing cp310 manylinux wheel

### ISSUE THREAD

**Issue by tammoippen** [scoder/lupa#203]
Thank you for the awesome project! :tada:

I just noticed, that the wheel for cp310 manylinux is missing - macos and win are available though and previous cp39 ... have the manylinux wheel.

https://pypi.org/project/lupa/#files:

![cp310-manylinux](https://user-images.githubusercontent.com/4425925/155298803-4e262a09-da48-4244-913c-5e0837e13dad.png)

**Comment by scoder** [comment]
Resolved in Lupa 1.11.
