### ISSUE TITLE
How to compute length of Python list in Lupa

### ISSUE THREAD

**Issue by vraja2** [scoder/lupa#210]
When trying to compute the length of a Python list passed through to Lua as follows:

```
#input_list
```

I'm getting the error:

```
lupa._lupa.LuaError: [string "<python>"]:214: attempt to get length of a POBJECT value
```

The type of `input_list` is `userdata`. How can I use the Lua syntax `#` for computing the length here? Thanks!

**Comment by synodriver** [comment]
```
from lupa import LuaRuntime
lua = LuaRuntime()
lua.globals()['len'] = len
func = lua.eval('function(a) return len(a) end')
func([1,2,2])
#3
```

**Comment by batrick** [comment]
Was there a reason to not implement the __len metamethod for a python object? `len` is apparently the python function?

**Comment by batrick** [comment]
(Why was `len` not put in `python.builtins`?)

**Comment by batrick** [comment]
nevermind I'm a bone-head :)
