### ISSUE TITLE
Option to limit memory usage

### ISSUE THREAD

**Issue by Le0Developer** [scoder/lupa#211]
I'd love to see an option to limit the max memory usage of a single LuaRuntime.

Lua supports passing a custom allocator function to [`lua_newstate`](https://www.lua.org/manual/5.1/manual.html#lua_newstate) which could refuse to allocate more memory when the limit is reached.

An example of this can be found [here on stackoverflow](https://stackoverflow.com/questions/9671793/limiting-a-lua-scripts-memory-usage).

**Comment by Le0Developer** [comment]
Currently implementing this in [my fork](https://github.com/Le0Developer/lupa/tree/feat/max-memory) and I stumpled over 2 problems:

- max_memory < ~2kb causes a `Failed to initialise Lua runtime` error (expected)
- max_memory < 24kb causes a lua panic by `lua.luaL_openlibs(L)`
- max_memory < 24440b causes a segmentation fault by `set_overflow_handler`

So max_memory between 2kb-24.5kb causes some not very nice bugs.

**Comment by scoder** [comment]
Sounds like a great idea.

We could probably avoid initialisation time crashes by disabling the limitation until the Lua runtime is initialised. I think that's a fair thing to do: apply the limit only to memory that the user can control, not something that Lupa needs.

**Comment by Le0Developer** [comment]
Sounds good, I'll finish writing tests and then work on that.
