### ISSUE TITLE
build: third-party\lua\lapi.c: No such file or directory since lupa-1.13

### ISSUE THREAD

**Issue by kamgha** [scoder/lupa#213]
Hi,

I'm seeing the following error during the build, which is also present on the buildbot. The last release without this issue is lupa-1.12.

`c1: fatal error C1083: Cannot open source file: 'C:\path\to\lupa\lupa\third-party\lua\lapi.c': No such file or directory`

Many jobs on the buildbot here on github have failed with the same error, for example: https://github.com/scoder/lupa/runs/5456023367?check_suite_focus=true#step:7:556

My environment is Python 3.7, Windows 7, Visual Studio 2015, Lua 5.4.4.

**Comment by scoder** [comment]
It might be that the file path is simply too long. Windows has problems here.

**Comment by kamgha** [comment]
Can not reproduce anymore and the buildbot here builds it again as well.
