### ISSUE TITLE
how i build with cython?

### ISSUE THREAD

**Issue by BlackMage2** [scoder/lupa#215]
how i build with cython? i have installed with pip3 cython, but with 'python3 setup.py' is always written 'building without Cython'

**Comment by scoder** [comment]
That's fine. Why do you want to use Cython here?

**Comment by BlackMage2** [comment]
how can i build **with** Cython?

**Comment by scoder** [comment]
You do not need Cython because the generated sources are already provided. The message is not hinting at a "missing feature" or so, it's just saying that it avoids unnecessary work. I'll close this as "works for me".

**Comment by BlackMage2** [comment]
ohh, so for c/c++ i can use the source headers? and link the compiled source?

**Comment by scoder** [comment]
What do you want to do?
