### ISSUE TITLE
Can not build with lua-lib option

### ISSUE THREAD

**Issue by synodriver** [scoder/lupa#218]
With the latest commit(3016db895f74447b661edf8b164affe6ce82ed0e), [lupa](https://github.com/scoder/lupa/blob/master/setup.py#L369) seems to generate ```lua.pyx``` when ```lua-lib``` and ```lua-includes``` is set, which conflict with ```lua.pxd``` because cython thinks ```lua.pyx``` is the implementation for ```lua.pxd```. Choosing another name for it should be fine. For instance, ```_lua.pyx```.

The environment:
```
pip list|grep Cython
Cython                       0.29.32

python -V
Python 3.10.4

uname -a
Linux codespaces-f9df62 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by synodriver** [comment]
What about changing ```ext_name = config.get('libversion', 'lua')``` to ```ext_name = config.get('libversion', '_lua')``` ? And so do ```__init__.py```

**Comment by scoder** [comment]
Hmm. Yes, calling it `lua.pyx` is a bad idea. We could call it `lupa` instead, although `lupa.lupa` would also seem confusing.

The intention is really to allow `from lupa import lua54`. The problem arises when we cannot know the library version before (configuring and) building the extension module, because the library was provided by the user in the form of a path to an arbitrary external file. If we know the header path, then we can try to parse those, but they might just be installed somewhere in the system.

I think a generic name is really the best we can (and should) do here.

**Comment by scoder** [comment]
Thanks for the timely report, BTW. I appreciate the testing and the feedback.

**Comment by synodriver** [comment]
I think we can add a prefix to all modules, like ```_```, so it becomes ```from lupa import _lua54``` and ```from lupa import _lua```. If the version is really necessary，maybe we can use ```ctypes``` to load those libraries to get the version.

**Comment by synodriver** [comment]
Anyway, the easiest way should be change the pxd file's name.

**Comment by scoder** [comment]
> I think we can add a prefix to all modules, like `_`, so it becomes `from lupa import _lua54` and `from lupa import _lua`.

That's not what you'd want to write as a user, is it?

> maybe we can use `ctypes` to load those libraries to get the version.

It's not about loading the Lua library. Each of the version modules is a complete (and usually statically linked) copy of the lupa module. `ctypes` won't help.

> Or we can just change `lua.pxd`'s name

It's possible that someone uses that `.pxd` file for talking to the Lua library directly. But I doubt that that's a big risk. Lupa doesn't expose its underlying Lua implementation anywhere. `luaapi.pxd` sounds good. I'll change the file name.

**Comment by synodriver** [comment]
BTW, there is another issue related to this commit. If you build with this option on windows, lupa will inject a ```lua51.dll``` (or maybe some name else) to the wheel, thus lupa will think ```lua51.dll``` is a valid python extension (but it's not) and fails to import unless you use ```from lupa.lua import LuaRuntime```.  So in my opinion, the ```_import_newest_lib``` should avoid grabing any ```.dll``` on windows.
