### ISSUE TITLE
What would be the best way to depend on `lupa` in another python module using Lua 5.2?

### ISSUE THREAD

**Issue by redruin1** [scoder/lupa#220]
I'm working on a module that emulates a game's load process, which uses Lua which I parse using `lupa`. However, the game runs on version 5.2, and lupa seems to only be bundled with the latest 5.4 at the moment. From what I understand, in order to fix this I either need to ensure that the end user has the correct version of Lua installed and builds lupa with said version (untenable), or I need to create said binaries across all platforms I wish to support and then distribute them alongside my module. Because my experience with lupa has been very much "it works out of the box", I was wondering if there was a slightly simpler way to just specify the Lua version to 5.2 and keep everything else the same. Any suggestions would be helpful.

**Comment by scoder** [comment]
Lupa 2.0 will include different Lua versions in separately importable Python modules. You can try the latest master branch to see how it will work.
