### ISSUE TITLE
lupa 1.13 can't be easily installed on python 3.11

### ISSUE THREAD

**Issue by henriquegemignani** [scoder/lupa#222]
With no wheels for 3.11 available, building the tarball is needed.
The included generated C file from Cython is not compatible with 3.11, re-generating it with a newer Cython is needed.

A workaround to install Lupa is:
1. `pip install Cython`
2. `pip install lupa --global-option="--with-cython" `

**Comment by sr-verde** [comment]
Thanks for your workaround, @henriquegemignani.

**Comment by ChrisLovering** [comment]
I see a [commit](https://github.com/scoder/lupa/commit/bf3113d6d12891963ac606fbe80f4384963890cc#) was made recently to build 3.11 wheels. Is a release being planned soon, for this CI to trigger and push wheels to pypi?

**Comment by scoder** [comment]
I just picked the same build changes over to the 1.x branch. If everything goes right with them, I'll push a new 1.14 release today, which should then have Py3.11 wheels.

**Comment by henriquegemignani** [comment]
Appreciated!

**Comment by AcidWeb** [comment]
Wheels are here but update was not pushed do PyPI.

**Comment by scoder** [comment]
I released 1.14.1 to PyPI.

**Comment by ChrisLovering** [comment]
Thanks for your work on this!
