### ISSUE TITLE
__getattr__ method may confuses py_to_lua

### ISSUE THREAD

**Issue by synodriver** [scoder/lupa#228]
If a pyobject implement ```__getattr__``` method, ```OBJ_AS_INDEX``` will always be true, which may leads to unexpected situations when calling python methods from lua because that object isn't really have ```__getitem__```

The following code
```
# prefer __getitem__ over __getattr__ by default
type_flags = OBJ_AS_INDEX if hasattr(o, '__getitem__') else 0
pushed_values_count = py_to_lua_custom(runtime, L, o, type_flags)
```
May be replaced by
```
# prefer __getitem__ over __getattr__ by default
type_flags = OBJ_AS_INDEX if hasattr(o, '__getitem__') and not hasattr(o, '__getattr__') else 0
pushed_values_count = py_to_lua_custom(runtime, L, o, type_flags)
```

What do you think about it?

**Comment by scoder** [comment]
All objects have a `__getattr__`, either implemented explicitly or by inheritance from `object` (thus, you could replace the whole condition with `False` in your replacement code). But if an object implements `__getitem___`, then chances are that users want to use item access rather than attribute access for it. That is the reason for the code above.

Users who want to use attribute access despite a `__getitem__` can make it explicit with the `as_attrgetter` wrapper function.

I don't see a confusion here.

**Comment by scoder** [comment]
Ah, right. Thanks. All objects have a `__getattribute__`, not necessarily a `__getattr__`. Still, I don't really see why `__getattr__` would be special. I'd still prefer a `__getitem__` in that case, because that's the intention of the code.

**Comment by synodriver** [comment]
For instance, the ```class C```, 

```
>>> class C:
...     def __getattr__(self, a):
...         return 42
...
>>> hasattr(C(), "__getitem__")
True
>>> C()["1"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'C' object is not subscriptable
```

**Comment by scoder** [comment]
> ```python
> >>> class C:
> ...     def __getattr__(self, a):
> ...         return 42
> ...
> >>> hasattr(C(), "__getitem__")
> True
> ```

But that's not because of `__getitem__` but because your `__getattr__` implementation is bad. It responds to any attribute, including `__getitem__`:

```python
>>> hasattr(C(), "__getitem__")
True
>>> hasattr(C(), "__getitem--xxxxx__")
True
```

**Comment by synodriver** [comment]
Ok, I see. That class looks like 
```
def __getattr__(self, name: str) -> "_ApiCall":
        return partial(self.call_api, name)
```

The reason to write so is to generate methods without having to write them. Unluckly, it generates a `__getitem__` somehow.  I will send a pr to them instead. Thanks for your answer.

**Comment by scoder** [comment]
It's good practice to exclude all attribute names staring (or sometimes starting and ending) with `__`. They can be passed on to the attribute lookup of the base class.
