### ISSUE TITLE
only lua 5.2 supported?

### ISSUE THREAD

**Issue by BlackMage2** [scoder/lupa#232]
> $ make
> python3 setup.py build_ext --inplace 
> Using bundled Lua in lua52
> Traceback (most recent call last):
>   File "/home/sven/Development/lupa/setup.py", line 351, in <module>
>     configs = [
>   File "/home/sven/Development/lupa/setup.py", line 352, in <listcomp>
>     use_bundled_lua(lua_bundle_path, c_defines)
>   File "/home/sven/Development/lupa/setup.py", line 270, in use_bundled_lua
>     with open(makefile) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/sven/Development/lupa/third-party/lua52/makefile'
> make: *** [Makefile:25: local] Error 1

are only lua 5.2 supported? i have lua 5.4 and luajit-2.1.0-beta3 installed

**Comment by scoder** [comment]
You probably just didn't update the git submodules locally. You can also pass `--no-bundle` to 'setup.py`.
