### ISSUE TITLE
Ship Lua 5.1 with default lupa installation

### ISSUE THREAD

**Issue by serozhenka** [scoder/lupa#256]
There is such a good library as the [`fakeredis-py`](https://github.com/cunla/fakeredis-py), which fully emulates Redis behavior in pure Python. One of the emulated things are Lua scripts, whose execution is done with lupa. However, as the only supported Lua runtime in Redis is 5.1, and 5.x versions are not fully backward-compatible there is breakage when testing scripts and executing them in real-world environments. So there is this suggestion to ship it with default installation along with other versions.

Another valid option might be to ship additional Lua versions by specifying package extras. As an example:
```
pip install "lupa[lua51,lua54]"
```

**Comment by scoder** [comment]
Lua 5.1 will be included in Lupa 2.1.

**Comment by serozhenka** [comment]
@scoder when the release is planned to happen?

**Comment by scoder** [comment]
Try the master branch. The CI build has wheels.
