### ISSUE TITLE
Terra

### ISSUE THREAD

**Issue by jmthackett** [scoder/lupa#258]
Hi folks,

I just found this project for the first time and first of all want to say I love it, as a dedicated python and lua user it is great to see.

I'm wondering if there's any plan, thinking, or just wild eyed experiments, relating to supporting Terra as part of lupa?

For context, I'm referring to terra lang (see: https://terralang.org ) which is a low level language designed to be embedded in Lua code. The terra binary itself embeds luajit, so seems like it'd be very close to what you're already doing. It'd open up some interesting (and maybe peculiar) opportunities for polyglot programming.

Not a feature request per se, more of a friendly hello and an open ended question. 

Cheers!

**Comment by scoder** [comment]
From a quick look, IIUC, this seems to use a completely different runtime implementation. Wrapping that is probably best done as a separate project.
