### ISSUE TITLE
Update pypi version to use LuaJIT 2.0.4

### ISSUE THREAD

**Issue by pablomayobre** [scoder/lupa#54]
LuaJIT 2.0.4 was released recently, it would be nice to have the pypi binary updated to use this version, plus reflect the newest changes (though there arent that many)

Thank you for your work! Keep it up :+1:

**Comment by kmike** [comment]
lupa doesn't bundle luajit, is there anything to update in lupa to support 2.0.4?

**Comment by jneb** [comment]
There now are download instructions on using luajit in the readme

**Comment by scoder** [comment]
Probably no longer an issue with Lupa 2.1.
