### ISSUE TITLE
Lupa running against wrong version of lua

### ISSUE THREAD

**Issue by jcelliott** [scoder/lupa#56]
I have lua5.1 and lua5.3 installed on my system. I believe I have installed lupa against lua5.1. Running setup.py install outputs `pkg-config found lua5.1 version 5.1.5`. However, when I try to use lupa, it appears to be using lua5.3 still: `lua.globals()._VERSION` outputs 'Lua 5.3'. Any ideas on how to get it to use 5.1?

**Comment by scoder** [comment]
Closing this as outdated. There are binary wheels including Lua 5.3.5 now, so this is probably not a problem any more.
