### ISSUE TITLE
Interesting bit in readme

### ISSUE THREAD

**Issue by emanuil-tolev** [scoder/lupa#58]
> you may also happily assume it's just an amalgamation of the phonetic sounds that start the words "Lua" and "Python", two from each to keep the balance

What's the 2nd letter coming from "Python"? L, u and a from Lupa are all only present in the word Lua. Anyhow, nice name and project!

**Comment by scoder** [comment]
Doesn't sound like this is worth a ticket, but when you pronounce "Python" the English way, the sounds are "P-a-i-th-o-n", so it's "L-u" + "P-a".
