### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by jayvdb** [scoder/lupa#75]
The package compiles and installs 'correctly' for the "pypy" and "pypy3" target on travis ( [see build](https://travis-ci.org/jayvdb/lupa/builds/121064162) ).

However when it is used the following exception occurs on "pypy":

``` python
Traceback (most recent call last):
...
  File "/home/travis/build/jayvdb/lupa/lupa/__init__.py", line 31, in <module>
    from lupa._lupa import *
ImportError: unable to load extension module '/home/travis/build/jayvdb/lupa/lupa/_lupa.pypy-25.so': /home/travis/build/jayvdb/lupa/lupa/_lupa.pypy-25.so: undefined symbol: PyByteArray_Check
```

This appears to have a hack which works around the problem, but maybe it only pushes the problem further along
https://mail.python.org/pipermail/pypy-dev/2014-August/012701.html

And on PyPy3:

``` python
Traceback (most recent call last):
...
  File "/home/travis/build/jayvdb/lupa/lupa/__init__.py", line 31, in <module>
    from lupa._lupa import *
ImportError: unable to load extension module '/home/travis/build/jayvdb/lupa/lupa/_lupa.pypy3-24.so': /home/travis/build/jayvdb/lupa/lupa/_lupa.pypy3-24.so: undefined symbol: PyBytes_FromFormat
```

which is https://bitbucket.org/pypy/pypy/issues/2022

If it isnt possible to workaround these issues easily, the setup.py could detect pypy and emit a useful error.  `README.rst` currently does mention Cpython a few times prominently , but it could be more clear and say that it definitely doesnt work on PyPy and probably wont compile on other implementations of Python .

**Comment by jayvdb** [comment]
On PyPy3, after getting around the PyBytes_FromFormat problem, the first lua func execution causes `Fatal Python error: PyThreadState_Get: no current thread` , which seems like a serious roadblock.

**Comment by scoder** [comment]
Don't expect pypy3 to work. It's way behind in development and badly maintained.

**Comment by jayvdb** [comment]
I found I can avoid invoking `PyByteArray_Check` on pypy2 by editing `_asciiOrNone`, but then pypy2 also breaks badly during the test suite, halting the python runtime for most test methods.

So, I guess the answer for this ticket is it isnt supported and wont be supported any time soon, and good luck to anyone who wants to try it.

**Comment by scoder** [comment]
I'm sure it's not that difficult, these are all tiny issues. I'll integrate the Check() fix into Cython 0.24.1. If something else is needed, it can still make it into that bug fix release.

**Comment by scoder** [comment]
Worth retrying, I guess. It might just work these days.

**Comment by TitanSnow** [comment]
By the way, the `cpyext` -- the pypy's emulation of CPython C API -- is much slow and buggy. The officially recommended way to write C ext for pypy is to use `cffi`, which behavior little slower on CPython, and much faster and stable on pypy because it's JIT friendly

**Comment by scoder** [comment]
The PyP developers have put a lot of effort into improving ``cpyext`` recently, and it's much better now. Many extension modules compile and run out of the box now. The emulation is substantially slower than the native C-API in CPython, sure, but that only applies to the boundary operations. In the case of Lupa, if you pass data into Lua, process it there for a while, and then pass the result back, that can easily be as fast in PyPy as in CPython. If, OTOH, you create an iterator in Lua and run over it in Python, then that usage will suffer from the emulation layer overhead.

**Comment by TitanSnow** [comment]
I have implemented a primary [cffi port of lupa](https://github.com/TitanSnow/lupa/tree/ffi)

**Comment by scoder** [comment]
@TitanSnow: You are obviously free to fork the Lupa project and maintain your own, separate version. I saw that you already use a different name (`ffilupa`), which is also a good idea.

**Comment by scoder** [comment]
Since there was no real activity on this issue for more than a year now, I'll close it, assuming that there is either lack of interest or lack of an actual problem (i.e. it probably just works).

**Comment by TitanSnow** [comment]
@scoder I found that using `cffi` is an easy way to expose low-level lua API like `luaL_loadbuffer` -- which is important for writing a lua REPL. I implemented [an easy lua REPL](https://github.com/TitanSnow/lupa/blob/ffi/demo_repl.py). Will `lupa` expose some low-level lua API in the future?

**Comment by scoder** [comment]
@TitanSnow, could you please open a new ticket for that feature request? Note that this is impossible to answer at that high level. If you need some specific functionality, that's something we can discuss. C-APIs are very easy to generate from Cython.
