### ISSUE TITLE
lupa._lupa in python 3.4

### ISSUE THREAD

**Issue by arthur-hav** [scoder/lupa#88]
After following the 5 step tutorial to install lupa with a static LuaJIT, I ran into the issue of "no module lupa._lupa" trying to import lupa in python 3.4 (Debian).

After building, with python 3, i got the following files inside site-packages/lupa:

    lupa/
      |——__init__.py
      |——_lupa.py
      |——_lupa.cpython-34m.so
      |——__pycache__/
      |——version.py`

The import inside `__init__.py` is `from lupa._lupa import *`. It might work on python 2, but I suspect absolute_import in python 3 makes this line expect specifically a _lupa sub-module. I moved around the files: 

    lupa/
      |——__init__.py
      |——_lupa/
          |——__init__.py (old _lupa.py)
          |——_lupa.cpython-34m.so
      |——__pycache__/
      |——version.py`

and it fixed the problem. I would then suggest that either the import or the file structure should be changed for python 3 support.

**Comment by kmike** [comment]
Could you please paste the whole traceback? 
Do you by chance run the import command when current folder is lupa checkout?

**Comment by scoder** [comment]
What are the exact commands that you used for installing Lupa?

**Comment by arthur-hav** [comment]
> Do you by chance run the import command when current folder is lupa checkout?

This is very possible, i admit i launched a python interpreter without really caring the folder, I will check for this

> What are the exact commands that you used for installing Lupa?

I went very straightforward. Something in the lines of:
    
    git clone lupa
    cd lupa
    git clone luagit
    cd luagit
    make
    cd ..
    python3 setup.py install

Since I didn't get it to work, i repeated these steps:
- In a virtualenv
- With different placement for luagit folder
- With liblua dev headers

Without any more success, all of them resulting in either my install not being linked with a correct lua runtime or having the lupa._lupa failure. But I did nothing more than that regarding the packages.

I will repeat the test taking care of the working directory and give you a full extract when I have more time.

**Comment by arthur-hav** [comment]
> Do you by chance run the import command when current folder is lupa checkout?

Confirmed this was the issue.

I suspect this might become a common pitfall, maybe it's worth a mention in the README.

**Comment by scoder** [comment]
Could you provide a pull request? It's unclear to me what the exact conditions were that you had problems with. Also, I'd rather put something in the build script that avoids these problems than simply documenting them.

**Comment by kmike** [comment]
@scoder it is not a problem with a build at all; the problem is that if you build and install lupa from source, extensions are installed to site-packages without polluting source checkout. But if you try to import lupa when the current folder is source checkout, import will fail as extensions are not available, and current folder has higher priority than site-packages in `sys.path`.

**Comment by arthur-hav** [comment]
Possible fixes on installation process:
- Name the source folder differently than the python package
- Have a dummy _lupa module in the source checkout warning the user
- Partly generate the lupa module so it behave differently once installed

I never developed a lib so I admit being completely incompetent regarding packaging them, I don't even know if my suggestions are actually possible within a python package. 

It seem to me having a minimal troubleshooting FAQ is the most rational bet regarding this particular chair keyboard interface issue.

**Comment by scoder** [comment]
Just for completeness, I usually do local testing with ``python3 setup.py build_ext --inplace``, which copies the .so file into the right package directory.

**Comment by scoder** [comment]
I pushed dd82e4366716bfec24ce9a0b604eeaf8a818f925, maybe that helps.
