### ISSUE TITLE
Can't not eval code loaded from external file

### ISSUE THREAD

**Issue by manhnt9** [scoder/lupa#97]
I'm having the same problem with this question: https://stackoverflow.com/questions/35492523/cannot-execute-lua-code-read-from-file

  File "lupa/_lupa.pyx", line 253, in lupa._lupa.LuaRuntime.eval
  File "lupa/_lupa.pyx", line 1276, in lupa._lupa.run_lua
lupa._lupa.LuaSyntaxError: error loading code: [string "<python>"]:1: <eof> expected near '='

**Comment by scoder** [comment]
Use `.execute()` instead of `.eval()`.
